### ISSUE TITLE
Milestone 2

### ISSUE THREAD

**Issue by tranminhan** [thuanmb/freebie#29]
Hi @chug2k, @harley

This is our live site https://chodocu.herokuapp.com/

Implemented features
# User
- As an user, I can register new account
- As an user, I can login into system with registered account
- As an user, I can login using FB.
- User can share a campaign on FB
# Campaign
- As an org, I can open/close a campaign to request donation from the community for a case.
- As a user, I can contact an org to donate money / stuff / my participation.
- As an org, I can list people donate for our campaign (after received their donation)
# Message
- User can send message to a person. (support markdown)
- User can check messages in inbox.
- User can reply a message.
- User can delete a message.
- User can see list of sent messages.

/cc @coderschoolreview

**Comment by coderschoolreview** [comment]
### Thank you for your Ruby submission, thuanmb!

:tired_face: Unfortunately **there are some problems** with your submission:
- I couldn't find a walkthrough GIF referenced from your `README.md`. Please use [RecordIt](http://recordit.co) or [LICEcap](http://www.cockos.com/licecap/) to record an animated GIF of your app in action, and include it in your `README.md`.

**Comment by chug2k** [comment]
My robot is going nuts. Sorry!
